# Generated by Django 6.0.2 on 2026-02-24 10:10

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_teacher_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                help_text="Student's parent/guardian phone number (Egyptian/KSA format: 01XXXXXXXXX)",
                max_length=15,
                validators=[
                    users.validators.validate_phone,
                    users.validators.validate_phone_optional,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                help_text="Student's phone number (Egyptian/KSA format: 01XXXXXXXXX)",
                max_length=15,
                validators=[
                    users.validators.validate_phone,
                    users.validators.validate_phone_optional,
                ],
            ),
        ),
    ]
