# Generated by Django 6.0.2 on 2026-02-12 20:10

import courses.models.course_models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_remove_student_emergency_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        help_text="Country name (e.g., Egypt, Saudi Arabia)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True,
                        help_text="Country flag image (max 2MB, formats: jpg, png, webp)",
                        null=True,
                        upload_to=courses.models.course_models.education_flag_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            courses.models.course_models.validate_image_size,
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EGP", "Egyptian Pound"), ("SAR", "Saudi Riyal")],
                        db_index=True,
                        default="EGP",
                        help_text="Currency used in this education system",
                        max_length=3,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this education system is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
                "ordering": ["country"],
                "indexes": [
                    models.Index(
                        fields=["country"], name="courses_edu_country_d9d931_idx"
                    ),
                    models.Index(
                        fields=["is_active", "country"],
                        name="courses_edu_is_acti_30ad6d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        help_text="Course title (e.g., Introduction to Calculus)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed course description, objectives, and requirements"
                    ),
                ),
                (
                    "course_img",
                    models.ImageField(
                        help_text="Course thumbnail image (max 2MB, min 200x200px)",
                        upload_to=courses.models.course_models.course_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            ),
                            courses.models.course_models.validate_image_size,
                            courses.models.course_models.validate_image_dimensions,
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="Course price (minimum 5.00 in local currency)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("5.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.99")
                            ),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the course is currently available for enrollment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher who created/manages this course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_courses",
                        to="users.teacher",
                    ),
                ),
                (
                    "education",
                    models.ForeignKey(
                        help_text="Education system this course belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_courses",
                        to="courses.education",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "-created_at"],
                        name="courses_cou_teacher_e90956_idx",
                    ),
                    models.Index(
                        fields=["education", "-created_at"],
                        name="courses_cou_educati_b228ae_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="courses_cou_is_acti_dc7440_idx",
                    ),
                    models.Index(
                        fields=["price", "-created_at"],
                        name="courses_cou_price_438bad_idx",
                    ),
                    models.Index(fields=["price"], name="courses_cou_price_1fbd18_idx"),
                    models.Index(fields=["title"], name="courses_cou_title_6e78a2_idx"),
                ],
                "unique_together": {("teacher", "title")},
            },
        ),
    ]
