# Generated by Django 6.0.2 on 2026-02-13 01:58

import courses.models.course_models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0002_chapter_lesson_chapter_courses_cha_order_dd42bd_idx_and_more",
        ),
        ("users", "0002_remove_student_emergency_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["course", "order"],
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["chapter", "order"],
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
        migrations.RemoveIndex(
            model_name="chapter",
            name="courses_cha_order_dd42bd_idx",
        ),
        migrations.RemoveIndex(
            model_name="chapter",
            name="courses_cha_order_812ef0_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="courses_cou_price_438bad_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="courses_cou_title_6e78a2_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="courses_les_order_348f18_idx",
        ),
        migrations.RemoveIndex(
            model_name="lesson",
            name="courses_les_order_d4444e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("course", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("chapter", "order"), ("chapter", "title")},
        ),
        migrations.AddField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter",
            name="description",
            field=models.TextField(
                blank=True, help_text="Chapter description (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, help_text="Lesson description (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                default=200,
                help_text="Video duration in seconds (1s to 4 hours)",
                validators=[courses.models.lesson_models.validate_video_duration],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                help_text="Parent course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters_of_course",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Display order within course",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Chapter title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_img",
            field=models.ImageField(
                help_text="Course thumbnail (max 2MB, min 200x200px)",
                upload_to=courses.models.course_models.course_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    courses.models.course_models.validate_image_size,
                    courses.models.course_models.validate_image_dimensions,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                help_text="Course description, objectives, and requirements"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="education",
            field=models.ForeignKey(
                help_text="Education system",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_courses",
                to="courses.education",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether course is available for enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                help_text="Course price (min 5.00)",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("5.00")),
                    django.core.validators.MaxValueValidator(Decimal("999999.99")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                help_text="Teacher who manages this course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_courses",
                to="users.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Course title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="chapter",
            field=models.ForeignKey(
                help_text="Parent chapter",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_of_chapter",
                to="courses.chapter",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Free preview lesson (accessible without enrollment)",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Display order within chapter",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                db_index=True, help_text="Lesson title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                help_text="Video URL (YouTube, Vimeo, Google Drive, etc.)",
                max_length=500,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("course", "order"), ("course", "title")},
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["course", "order"], name="courses_cha_course__15aa4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["chapter", "order"], name="courses_les_chapter_c6ac9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["is_preview"], name="courses_les_is_prev_924950_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="duration",
        ),
    ]
