# Generated by Django 6.0.2 on 2026-02-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_chapter_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Subject name (e.g., Mathematics, Physics)', max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, help_text='Subject name in Arabic', max_length=100, null=True)),
                ('code', models.CharField(help_text='Unique subject code (e.g., MATH101)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Subject description')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this subject is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='courses_sub_is_acti_45d317_idx')],
            },
        ),
    ]
