# Generated by Django 6.0.2 on 2026-02-18 00:04

import courses.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_subject"),
        ("users", "0006_alter_student_user_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current enrollment status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("paypal", "PayPal"),
                            ("bank_transfer", "Bank Transfer"),
                            ("vodafone_cash", "Vodafone Cash"),
                            ("orange_cash", "Orange Cash"),
                        ],
                        db_index=True,
                        help_text="Payment method used",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment gateway transaction ID",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual amount paid by student",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.99")
                            ),
                        ],
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original course price at time of enrollment",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(
                                Decimal("999999.99")
                            ),
                        ],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount applied (if any)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(
                        blank=True, help_text="Coupon code used (if any)", max_length=50
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Refund amount (if refunded)",
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, help_text="Reason for refund"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, help_text="When refund was processed", null=True
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student last accessed course content",
                        null=True,
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Course completion percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When student completed the course",
                        null=True,
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When enrollment was created"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was confirmed and enrollment activated",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=1,
                        default=5,
                        max_digits=1,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["country"],
                "verbose_name": "Education System",
                "verbose_name_plural": "Education Systems",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when course was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether course is visible to students",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When course was first published", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly version of title (auto-generated)",
                max_length=250,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subject_courses",
                to="courses.subject",
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="country_code",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="ISO 3166-1 alpha-3 country code (e.g., EGY, SAU)",
                max_length=3,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when education system was soft-deleted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="education",
            field=models.ForeignKey(
                help_text="Education system this course belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_courses",
                to="courses.education",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EGP", "Egyptian Pound"),
                    ("SAR", "Saudi Riyal"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                ],
                db_index=True,
                default="EGP",
                help_text="Currency used in this education system",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="flag",
            field=models.ImageField(
                blank=True,
                help_text="Country flag image (max 2MB)",
                null=True,
                upload_to=courses.validators.education_flag_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    courses.validators.validate_image_size,
                    courses.validators.validate_image_dimensions,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.CharField(
                help_text="Unique subject code (e.g., MATH, PHYS, CHEM)",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True, help_text="Subject description and scope"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["subject", "-created_at"], name="courses_cou_subject_c27365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_active", "is_published", "-created_at"],
                name="courses_cou_is_acti_42b7aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="education",
            index=models.Index(
                fields=["country_code"], name="courses_edu_country_3f950c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["code"], name="courses_sub_code_e1a9ef_idx"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                help_text="Course enrolled in",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_enrollments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Student who enrolled",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="users.student",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                help_text="course will Review it",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_reviews",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="student",
            field=models.ForeignKey(
                help_text="Student who Review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students_review",
                to="users.student",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "-enrolled_at"],
                name="courses_enr_student_cd5776_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "-enrolled_at"], name="courses_enr_course__cdfeb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["status", "-enrolled_at"], name="courses_enr_status_6b53a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "course"], name="courses_enr_student_774ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "status"], name="courses_enr_student_c86bf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "status"], name="courses_enr_course__78d524_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["transaction_id"], name="courses_enr_transac_1da9c4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["student", "-created_at"], name="courses_rev_student_b3d0de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["course", "-created_at"], name="courses_rev_course__092c7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["student", "course"], name="courses_rev_student_d04c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["student"], name="courses_rev_student_860f02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["course"], name="courses_rev_course__8906ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["course", "rating"], name="courses_rev_course__b944e5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("student", "rating", "course")},
        ),
    ]
