# Generated by Django 6.0.2 on 2026-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_review_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('vodafone_cash', 'Vodafone Cash'), ('orange_cash', 'Orange Cash')], db_index=True, help_text='Payment method used', max_length=50),
        ),
    ]
