# Generated by Django 6.0.2 on 2026-02-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_course_img"),
        ("users", "0008_alter_student_parent_phone_alter_student_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Student who enrolled",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_enrollments",
                to="users.student",
            ),
        ),
    ]
