# Generated by Django 6.0.2 on 2026-02-24 12:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0010_alter_enrollment_student"),
        ("users", "0008_alter_student_parent_phone_alter_student_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="price_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Actual amount paid by student",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("999999.99")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Payment gateway transaction ID",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_id__isnull", False)),
                fields=("transaction_id",),
                name="unique_transaction_id",
            ),
        ),
    ]
